version: "2"

services:
  mssql:
    image: microsoft/mssql-server-linux
    volumes:
      - /mssql-server/data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123
    ports:
      - "1433:1433"
